config/urls.py
from django.contrib import admin
from django.urls import path, include


from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('bookmark.urls')),
    path('photo/',include('photo.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# DEBUG 모드일때 - static 기능을 사용한다.
# 1. 미디어 파일 서버를 별도로 두고 사용한다.
# 2. 웹서버에서 별도로 서빙 설정을 한다.

photo/urls.py
from django.urls import path
from django.views.generic.detail import DetailView
from .views import *
from .models import Photo
# 2차 url 파일

app_name = 'photo'

urlpatterns = [
    path('', photo_list, name='photo_list'),
    path('detail/<int:pk>', DetailView.as_view(model=Photo, template_name='photo/detail.html'), name='photo_detail'),
    path('upload/', PhotoUploadView.as_view(), name='photo_upload'),
    path('delete/<int:pk>/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),

]

photo/models.py
from django.db import models

# Create your models here.

# 1. 모델 : 데이터베이스 저장될 데이터가 있다면 해당 데이터를 묘사한다.
# 2. 뷰(기능) : 계산, 처리 - 실제 기능, 화면
# 3. url 맵핑 : 라우팅 테이블에 기록한다. urls.py에 기록 - 주소를 지정
# 4. 화면에 보여줄 것이있다 : 템플릿작성(html)


# 장고의 기본 유저 모델
from django.contrib.auth.models import User
from django.urls import reverse


# 왜래키 (ForeingKey) - User 테이블에서 해당 유저를 찾을 수 있는 주키
# 주키 (PrimaryKey) - User 테이블에 1 admin x x x x
class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_photos')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', default='photos/no_image.png')
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # makemigrations -> migrate
    class Meta:
        ordering = ['-updated']  #- 면 디샌딩 제일 마지막으로 설정 , 찍어서 중첩할수있음

    def __str__(self): #프린트를 해보거나 관리자 페이지에서 출력할때 씀
        return self.author.username + "" + self.created.strftime("%Y-%m-%d %H:%M:%S") #몇년 몇월 몇일 몇시 몇분 몇초에 생성되게끔 설정해주면됨

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=[self.id])

photo/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
from .models import Photo

@login_required
def photo_list(request):
    # 보여줄 사진 데이터 필요
    photos = Photo.objects.all()
    return render(request, 'photo/list.html', {'photos':photos})

class PhotoUploadView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['photo','text'] #작성장(author), 작성시간(created) 있어야하지만 로그인해서 씀으로 자동처리됨 작성시간도 어떠한 동작때문에 자동으로 됨
    template_name = 'photo/upload.html'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id # 규칙이다 외워라
        if form.is_valid():
            #데이터가 올바르다면 저장을 하겠다. photo 모델에 인스턴스가 존재하며 저장을하게됨
            form.instance.save()
            return redirect('/') # succes url 이 동작했어야되는게 이거임
        else:
            return self.render_to_response({'form':form})


class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    success_url = '/'
    template_name = 'photo/delete.html'


class PhotoUpdateView(LoginRequiredMixin, UpdateView):
    model = Photo
    fields = ['photo','text']
    template_name = 'photo/update.html'


"""
서버에 이미지 파일을 업로하거나 수정하거나 지운다.
장고 웹 앱이 한다.
장고 웹 앱은 특정 서버에 업로드 되어 있다. 
* 그럼 해당 기능은 특정 서버 안에서만 영향을 끼칠수 있다.
-> 실 서비스를 배포하면 서버 컴퓨터는 1대가 아니다.
-> 사용자가 늘어날 떄마다 서버 컴퓨터도 늘어난다.
-> 장고 웹 앱이 업로드 되어있는 서버 컴퓨터가 늘어난다.
-> 이미지 파일이 업로도 되는 컴퓨터의 댓수도 늘어나야 한다.
-> 업로드 받은 후에 다른 서버에도 공유해줘야 한다.
-> 공유해주는데 사용되는 자원(돈이나 시간)이 아깝다.
-> 어떻게 하면 공유하는데 들어가는 돈이나 시간을 절약할 수 있을까?
-> 이미지는 한곳의 서버에다만 올려놓고, 거기에 접속해서 사용하자. 
"""

photo/templates/photo/delete.html
{% extends 'base.html' %}
{% block title %}- Delete{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="alert alert-info">
                Do you want to delete {{object}}?
            </div>
            <form action="" method="post">
                {{form.as_p}}
                {%csrf_token%}
                <input type="submit" class="btn btn-primary" value="Confirm">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

photo/templates/photo/detail.html
{% extends 'base.html' %}
{% block title %}
    {{object.text|truncatechars:10}}
{% endblock %}

{% block content %}
     <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel panel-default">
            <p><img src="{{object.photo.url}}" style="width: 100%;"></p>
            <button type="button" class="btn btn-xs btn-info">
                {{object.author.username}}
            </button>
            <p>{{object.text|linebreaksbr}}</p>
            <a href="{% url 'photo:photo_delete' pk=object.id %}" class="btn btn-outline-danger btn-sm float-right">Delete</a>
            <a href="{% url 'photo:photo_update' pk=object.id %}" class="btn btn-outline-success btn-sm float-right">Update</a>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {% load disqus_tags %}
            {% disqus_show_comments %}
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

photo/templates/photo/list.html
{% extends 'base.html' %}
{% block title %} blog{% endblock %}
{% block content %}
    {% for post in photos %}
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 panel panel-default">
                <p><img src="{{post.photo.url}}" style="width: 100%;"></p>
                <button type="button" class="btn btn-xs btn-info">
                    {{post.author.username}}
                </button>
                <p>{{post.text|linebreaksbr}}</p>
                <p class="text-right">
                    <a href="{% url 'photo:photo_detail' pk=post.id %}" class="btn btn-xs btn-success">댓글달기</a>
                </p>
            </div>
            <div class="col-md-2"></div>
        </div>
    <!--    <section class="sub-page-banner parallax" id="banner">-->
    <!--			<div class="container">-->
    <!--				<div class="row">-->
    <!--					<div class="col-md-12">-->
    <!--						<div class="page-banner text-center">-->
    <!--							<h1 class="sub-banner-title">Blog</h1>-->
    <!--							<ul>-->
    <!--								<li><a href="index.html">Home</a></li>-->
    <!--								<li>Blog</li>-->
    <!--							</ul>-->
    <!--						</div>-->
    <!--					</div>-->
    <!--				</div>-->
    <!--			</div>-->
    <!--		</section>-->

    <!--		<section class="blog-list-main ptb-100">-->
    <!--			<div class="container">-->
    <!--				<div class="row">-->
    <!--					<div class="col-xl-4 col-lg-4 col-md-12 order-r-2">-->
    <!--						<div class="blog-search mb-45">-->
    <!--							<input type="text" name="search" placeholder="Search...">-->
    <!--							<button class="blog-search-btn"><i class="fa fa-search" aria-hidden="true"></i></button>-->
    <!--						</div>-->
    <!--						<div class="blog-category mb-45">-->
    <!--							<h2 class="blog-cat-title">Category</h2>-->
    <!--							<ul>-->
    <!--								<li><a href="blog-detail.html">Blockchain</a></li>-->
    <!--								<li><a href="blog-detail.html">Cryptocurrency</a></li>-->
    <!--								<li><a href="blog-detail.html">Technology</a></li>-->
    <!--								<li><a href="blog-detail.html">Competitive Research</a></li>-->
    <!--								<li><a href="blog-detail.html">Startup</a></li>-->
    <!--							</ul>-->
    <!--						</div>-->
    <!--						<div class="trending-news mb-45">-->
    <!--							<h2 class="blog-cat-title">Trending News</h2>-->
    <!--							<div class="trending-news-box mb-20">-->
    <!--								<div class="trending-news-img">-->
    <!--									<a href="#"><img src="images/news-1.jpg" class="transition" alt="Trending News"></a>-->
    <!--								</div>-->
    <!--								<div class="trending-news-content">-->
    <!--									<a href="#" class="trending-news-title">Finance Minister Calls of ICO.</a>-->
    <!--									<span class="trending-news-date">March 20,2019</span>-->
    <!--								</div>-->
    <!--								<div class="clear"></div>-->
    <!--							</div>-->
    <!--							<div class="trending-news-box mb-20">-->
    <!--								<div class="trending-news-img">-->
    <!--									<a href="#"><img src="images/news-1.jpg" class="transition" alt="Trending News"></a>-->
    <!--								</div>-->
    <!--								<div class="trending-news-content">-->
    <!--									<a href="#" class="trending-news-title">Finance Minister Calls of ICO.</a>-->
    <!--									<span class="trending-news-date">March 20,2019</span>-->
    <!--								</div>-->
    <!--								<div class="clear"></div>-->
    <!--							</div>-->
    <!--							<div class="trending-news-box mb-20">-->
    <!--								<div class="trending-news-img">-->
    <!--									<a href="#"><img src="images/news-1.jpg" class="transition" alt="Trending News"></a>-->
    <!--								</div>-->
    <!--								<div class="trending-news-content">-->
    <!--									<a href="#" class="trending-news-title">Finance Minister Calls of ICO.</a>-->
    <!--									<span class="trending-news-date">March 20,2019</span>-->
    <!--								</div>-->
    <!--								<div class="clear"></div>-->
    <!--							</div>-->
    <!--						</div>-->
    <!--						<div class="blog-tags mb-45">-->
    <!--							<h2 class="blog-cat-title">Trending News</h2>-->
    <!--							<ul>-->
    <!--								<li><a href="javascript:void(0)">crypto</a></li>-->
    <!--								<li><a href="javascript:void(0)">Consultation</a></li>-->
    <!--								<li><a href="javascript:void(0)">Case</a></li>-->
    <!--								<li><a href="javascript:void(0)">Attorney</a></li>-->
    <!--								<li><a href="javascript:void(0)">Crypto Currency</a></li>-->
    <!--								<li><a href="javascript:void(0)">BTC</a></li>-->
    <!--								<li><a href="javascript:void(0)">Dollar</a></li>-->
    <!--								<li><a href="javascript:void(0)">Ethereum</a></li>-->
    <!--							</ul>-->
    <!--						</div>-->
    <!--						<div class="archives">-->
    <!--							<h2 class="blog-cat-title">Archives</h2>-->
    <!--							<ul>-->
    <!--								<li><a href="#">January 2018</a></li>-->
    <!--								<li><a href="#">January 2018</a></li>-->
    <!--								<li><a href="#">January 2018</a></li>-->
    <!--							</ul>-->
    <!--						</div>-->
    <!--					</div>-->
    <!--					<div class="col-xl-8 col-lg-8 col-md-12 order-r-1">-->
    <!--						<div class="blog-list-box">-->
    <!--							<div class="blog-list-img">-->
    <!--								<a href="blog-detail.html"><img src="images/blog-4.jpg" class="transition" alt="blog"></a>-->
    <!--							</div>-->
    <!--							<div class="blog-list-content">-->
    <!--								<a href="blog-detail.html" class="blog-list-title">Cryptocash is a clean, modern and itry-specific HTML template</a>-->
    <!--								<ul>-->
    <!--									<li>March 20,2019</li>-->
    <!--									<li>by john Doe</li>-->
    <!--								</ul>-->
    <!--								<p class="blog-list-des">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip </p>-->
    <!--								<a href="blog-detail.html" class="read-more">Read More</a>-->
    <!--							</div>-->
    <!--						</div>-->
    <!--						<div class="blog-list-box">-->
    <!--							<div class="blog-list-img">-->
    <!--								<a href="blog-detail.html"><img src="images/blog-5.jpg" class="transition" alt="blog"></a>-->
    <!--							</div>-->
    <!--							<div class="blog-list-content">-->
    <!--								<a href="blog-detail.html" class="blog-list-title">Cryptocash is a clean, modern and itry-specific HTML template</a>-->
    <!--								<ul>-->
    <!--									<li>March 20,2019</li>-->
    <!--									<li>by john Doe</li>-->
    <!--								</ul>-->
    <!--								<p class="blog-list-des">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip </p>-->
    <!--								<a href="blog-detail.html" class="read-more">Read More</a>-->
    <!--							</div>-->
    <!--						</div>-->
    <!--						<div class="blog-list-box">-->
    <!--							<div class="blog-list-img">-->
    <!--								<a href="blog-detail.html"><img src="images/blog-6.jpg" class="transition" alt="blog"></a>-->
    <!--							</div>-->
    <!--							<div class="blog-list-content">-->
    <!--								<a href="blog-detail.html" class="blog-list-title">Cryptocash is a clean, modern and itry-specific HTML template</a>-->
    <!--								<ul>-->
    <!--									<li>March 20,2019</li>-->
    <!--									<li>by john Doe</li>-->
    <!--								</ul>-->
    <!--								<p class="blog-list-des">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip </p>-->
    <!--								<a href="blog-detail.html" class="read-more">Read More</a>-->
    <!--							</div>-->
    <!--						</div>-->

    <!--						<div class="blog-list-pagination">-->
    <!--							<ul>-->
    <!--								<li><a href="#" class="active">1</a></li>-->
    <!--								<li><a href="#">2</a></li>-->
    <!--								<li><a href="#">3</a></li>-->
    <!--								<li><a href="#"><i class="fa fa-angle-right" aria-hidden="true"></i></a></li>-->
    <!--							</ul>-->
    <!--						</div>-->
    <!--					</div>-->
    <!--				</div>-->
    <!--			</div>-->
    <!--		</section>-->
    {% endfor %}
{% endblock %}

photo/templates/photo/update.html
{% extends 'base.html' %}
{% block title %}- blog{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" enctype="multipart/form-data">
                {{form.as_p}}
                {%csrf_token%}
                <input type="submit" class="btn btn-primary" value="Update">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

photo/templates/photo/upload.html
{% extends 'base.html' %}
{% block title %}- blog{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form action="" method="post" enctype="multipart/form-data">
                {{form.as_p}}
                {%csrf_token%}
                <input type="submit" class="btn btn-primary" value="Upload">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}